const userRouter = require('./api/userRouter');
const categoryRouter = require('./api/categoryRouter');
const typeRouter = require('./api/typeRouter');
const attractionsRouter = require('./api/attractionsRouter');
const addressRouter = require('./api/addressApi');
const cloudRouter = require('./api/cloudRouter');
const otpRouter = require('./api/otpRouter');
const shopRouter = require('./api/shopRouter');
const sellerApplicationRouter = require('./api/sellerapplicationRouter');
const productRouter = require('./api/productRouter');
const unitRouter = require('./api/unitApi');
module.exports = (app) => {
  app.use('/api/user', userRouter);
  app.use('/api/category', categoryRouter);
  app.use('/api/type', typeRouter);
  app.use('/api/attractions', attractionsRouter);
  app.use('/api/address', addressRouter);
  app.use('/api/cloud', cloudRouter);
  app.use('/api/otp', otpRouter);
  app.use('/api/shop', shopRouter);
  app.use('/api/sellerapplication', sellerApplicationRouter);
  app.use('/api/product', productRouter);
  app.use('/api/unit', unitRouter);
};
